### ISSUE TITLE
Consider auto detecting polyfillable features

### ISSUE THREAD

**Issue by triblondon** [Financial-Times/origami-build-tools#194]
See https://github.com/azproduction/autopolyfiller.  It uses our polyfill library but uses code inspection to determine which polyfills are required.  Could be built into obt.

**Comment by AlbertoElias** [comment]
Should we discuss this? I'm a bit wary of adding even more dependencies, but if it's worth it..

**Comment by triblondon** [comment]
Not urgent - but leave it open, I think it's worth considering in the future.  If it languishes unloved forever, we'll close it eventually I guess.

**Comment by onishiweb** [comment]
Worth bringing this up again?

**Comment by AlbertoElias** [comment]
We haven´t really had issues with this, so for me it's a no

**Comment by JakeChampion** [comment]
Solving this in a general way would be amazing as every consumer of polyfill.io could use it, we do have issues where people forget to add a JS API into the `features` query parameter, which causes their site to break for some browsers. Solving it in the general way would probably involve some kind of AST traversal tool such as Babel or Acorn.

If we want to solve this for Origami components alone, it might be simpler to use the `browserFeatures` field in `origami.json` instead of doing some JS AST traversal/parsing.
